import React from 'react'
import Script from 'next/script';
const page = () => {
  return (
    <div>
        <Script>
            {`alert("Welcome to Contact Page ")`}
        </Script>
      this is a page of Conact
    </div>
  )
}
export const metadata = {
    title: "Faceboot - Contact page",
    description: "Generated by create next app",
  };

export default page
