import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Next App",
  description: "Admin Generated by create next app",
};

export default function loginLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       
        {children}
      </body>
    </html>
  );
}
