import React from 'react'
import Script from 'next/script';
//Script tag used to write the java script
const about = () => {
  return (
    <div>
      <Script>
        {`alert("Welcome to the About page ")`}
      </Script>
      This page is of about
    </div>
  )
}
export const metadata = {
  title: "Faceboot - About page",
  description: "Generated by create next app",
};
  export default about
